/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#2170e4",
        background: "#fcf9f8",
        "on-surface-variant": "#424754",
        "inverse-on-surface": "#f3f0ef",
        "surface-container": "#f0edec",
        "inverse-primary": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe7e7",
        "surface-variant": "#e5e2e1",
        primary: "#0058be",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        secondary: "#495e8a",
        "primary-fixed-dim": "#adc6ff",
        "on-surface": "#1c1b1b",
        "inverse-surface": "#313030",
        "on-primary-container": "#fefcff",
        error: "#ba1a1a",
        "secondary-container": "#b6ccff",
        "on-background": "#1c1b1b",
        "on-secondary-container": "#405682",
        "secondary-fixed": "#d8e2ff",
        "on-primary-fixed": "#001a42",
        outline: "#727785",
        surface: "#fcf9f8",
        "outline-variant": "#c2c6d6",
        "surface-container-highest": "#e5e2e1",
        "pixel-green": "#00ff41",
        "pixel-cyan": "#00e5ff",
        "pixel-yellow": "#ffe600",
        "pixel-red": "#ff2d55",
        "pixel-purple": "#b84fff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        pixel: ["'Press Start 2P'", "monospace"],
        vt: ["'VT323'", "monospace"],
      },
    },
  },
  plugins: [],
};
